"""empty message

Revision ID: 4a765613d064
Revises: e6bd4b6a0859
Create Date: 2022-08-22 11:52:04.931826

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a765613d064'
down_revision = 'e6bd4b6a0859'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_username_key', 'user', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('user_username_key', 'user', ['username'])
    # ### end Alembic commands ###
