"""empty message

Revision ID: e6bd4b6a0859
Revises: 8c6406cec1fb
Create Date: 2022-08-22 11:51:21.290197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6bd4b6a0859'
down_revision = '8c6406cec1fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('platform', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'platform')
    # ### end Alembic commands ###
